name: vocaboom
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  flutter_tts: ^4.0.2
  google_sign_in: ^6.2.1    # Thư viện Google
  flutter_facebook_auth: ^7.1.5 # Thư viện Facebook
  speech_to_text: ^7.0.0  # Để chuyển giọng nói thành văn bản (cho câu Speaking)
  permission_handler: ^12.0.1 # Xin quyền Micro
  google_translator: ^1.0.0
  translator: ^1.0.4+1
  shared_preferences: ^2.5.4
  firebase_auth: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true